name: action

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        default: ''
        
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: get date
      run: echo ARGS=${DATE:+--revert=$DATE} >> ${GITHUB_ENV}
      env:
        DATE: ${{ inputs.date }}

    - name: run in docker container
      uses: docker://applehq/gentoo-stage4
      with:
        args: emerge-webrsync ${{ env.ARGS }}
