name: action

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        default: ''
        
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
      env:
        DATE: ${{ inputs.date }}

    steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: get portage tree
      run: emerge-webrsync --quiet ${DATE:+--revert=$DATE}

    - name: check kirigami
      run: ./.github/workflows/bestmatch-visible.py kde-frameworks/kirigami >> $GITHUB_STEP_SUMMARY

    - name: check systemd
      run: ./.github/workflows/bestmatch-visible.py sys-apps/systemd >> $GITHUB_STEP_SUMMARY
