name: action

on:
  push:
  schedule:
  - cron: "46 *  2      * *" # every hour on a 2nd day of the month
  - cron: "46 13 1,3-31 * *" # 13:46 on all other days
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        
jobs:
  check:
    runs-on: ubuntu-latest
    container: gentoo/stage3

    steps:
    - name: get date
      run: (test "$DATE" && echo "NEWDATE=$DATE" || echo NEWDATE=$(date --date="1 day ago" +%Y%m%d)) | tee -a $GITHUB_ENV
      env:
        DATE: ${{ inputs.date }}

    - name: cache getuto keys
      uses: actions/cache@v4
      with:
        key: getuto-${{ env.NEWDATE }}
        path: /etc/portage/gnupg
        restore-keys: getuto-

    - name: cache whole tree
      id: cache-tree
      uses: actions/cache@v4
      with:
        key: portage-${{ env.NEWDATE }}
        path: /var/db/repos/gentoo

    - name: cache tree snapshot
      id: cache-snapshot
      uses: actions/cache@v4
      with:
        key: distfiles-${{ env.NEWDATE }}
        path: /var/cache/distfiles
        restore-keys: distfiles-

    - name: get portage tree
      if: ${{ steps.cache-tree.outputs.cache-hit != 'true' }}
      run: emerge-webrsync --quiet --keep ${NEWDATE:+--revert=$NEWDATE}

    - name: install git
      run: |
        getuto
        emerge --update --quiet --getbinpkg dev-vcs/git

    - name: checkout source
      uses: actions/checkout@v4

    - name: Find best versions
      run: |
        echo "## Found best versions for $NEWDATE" >> $GITHUB_STEP_SUMMARY
        grep -qR $(./.github/workflows/bestmatch-visible.py kde-frameworks/kirigami)
        git grep -q $(./.github/workflows/bestmatch-visible.py sys-apps/systemd)
