name: action

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        default: ''
        
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
      env:
        DATE: ${{ inputs.date }}

    steps:
    - name: get date
      run: |
        emerge-webrsync ${DATE:+--revert=$DATE}
        emerge --info
