name: action

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3

    steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: get date
      run: test "$DATE" && echo "NEWDATE=$DATE" || echo NEWDATE=$(date --date="1 day ago" +%Y%m%d) >> $GITHUB_ENV
      env:
        DATE: ${{ inputs.date }}

    - name: cache whole tree
      id: cache-tree
      uses: actions/cache@v4
      with:
        key: tree-${{ env.NEWDATE }}
        path: /var/db/repos/gentoo
        restore-key: tree

    - name: cache tree snapshot
      id: cache-snapshot
      if: ${{ steps.cache-tree.outputs.cache-hit != 'true' }}
      uses: actions/cache@v4
      with:
        key: portage-${{ env.NEWDATE }}
        path: /var/cache/distfiles
        restore-keys: |
          portage-

    - name: get portage tree
      if: ${{ steps.cache-tree.outputs.cache-hit != 'true' }}
      run: emerge-webrsync --quiet --keep ${NEWDATE:+--revert=$NEWDATE}

    - name: Summary header
      run: echo "## Found best versions for $NEWDATE" >> $GITHUB_STEP_SUMMARY

    - name: check kirigami
      run: ./.github/workflows/bestmatch-visible.py kde-frameworks/kirigami

    - name: check systemd
      run: ./.github/workflows/bestmatch-visible.py sys-apps/systemd
