name: action

on:
  push:
  workflow_dispatch:
    inputs:
      date:
        description: date
        required: false
        default: ''
        
jobs:
  check:
    runs-on: ubuntu-latest
    container: gentoo/stage3
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: get date
      run: |
        emerge-webrsync ${DATE:+--revert=$DATE}
        emerge --info
      env:
        DATE: ${{ inputs.date }}
