name: nixos workflows

on:
  push:
  workflow_dispatch:

jobs:
  unsandboxed:
    runs-on: ubuntu-latest
    container: nixos/nix
    steps:
    - name: update nix-channel
      run: nix-channel --update

    - name: build-a-package
      run: nix-build '<nixpkgs>' -A modemmanager

  sandboxed:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
      options: --privileged
    steps:
    - name: update nix-channel
      run: nix-channel --update

    - name: enable sandbox
      run: |
        mv /etc/nix/nix.conf /etc/nix/nix.conf.bak
        cp -L /etc/nix/nix.conf.bak /etc/nix/nix.conf
        ls -l /etc/nix/nix.conf
        cat /etc/nix/nix.conf
        nix-env -iA gnused
        sed -i '/^sandbox/s/false/true/' /etc/nix/nix.conf

    - name: build-a-package
      run: nix-build '<nixpkgs>' -A modemmanager
