name: nixos workflows

on:
  push:
  workflow_dispatch:

jobs:
  unsandboxed:
    runs-on: ubuntu-latest
    container: nixos/nix
    steps:
    - name: update nix-channel
      run: nix-channel --update

    - name: need node inside container
      run: |
        nix-env -iA nixpkgs.nodejs_20
        ls -l /__e/node20/bin/node

    - name: checkout sources
      uses: actions/checkout@v4

    - name: build-a-package
      run: nix-build --expr 'import <nixpkgs>{config=import ./mm.nix;}' -A modemmanager

  sandboxed:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
      options: --privileged
    steps:
    - name: update nix-channel
      run: nix-channel --update

    - name: enable sandbox
      run: |
        mv /etc/nix/nix.conf /etc/nix/nix.conf.bak
        cp -L /etc/nix/nix.conf.bak /etc/nix/nix.conf

        nix-env -iA nixpkgs.gnused
        sed -i '/^sandbox/s/false/true/' /etc/nix/nix.conf

    - name: need node inside container
      run: |
        nix-env -iA nixpkgs.nodejs_20
        ls -l /__e/node20/bin/node

    - name: checkout sources
      uses: actions/checkout@v4

    - name: build-a-package
      run: nix-build --expr 'import <nixpkgs>{config=import ./mm.nix;}' -A modemmanager
